name = "leeandnote-publish-scheduler"
main = "src/index.js"
compatibility_date = "2026-09-15"

[triggers]
crons = ["10 11 * * *", "30 11 * * *", "*/10 22-23 * * SUN-THU", "*/10 0-10 * * MON-FRI", "0 11 * * MON-FRI"]

[vars]
GITHUB_REPOSITORY = "leeandnote/dart-holdings-preview"
GITHUB_WORKFLOW = "daily-publish.yml"
GITHUB_INTRADAY_WORKFLOW = "intraday-alert.yml"
GITHUB_REF = "main"
